UPDATE mentions
SET nom = CASE abr
    WHEN 'BTP' THEN 'BATIMENT ET TRAVAUX PUBLICS'
    WHEN 'EN' THEN 'ELECTRONIQUE'
    WHEN 'GE' THEN 'GENIE ELECTRIQUE'
    WHEN 'GER' THEN 'GENIE RURAL'
    WHEN 'GGEO' THEN 'GENIE GEOLOGIQUE'
    WHEN 'GMI' THEN 'GENIE MECANIQUE'
    WHEN 'GPCI' THEN 'GENIE DES PROCEDES CHIMIQUES ET INDUSTRIELS'
    WHEN 'HYD' THEN 'HYDRAULIQUE'
    WHEN 'IGAT' THEN 'INFORMATION GEOGRAPHIQUE ET AMENAGEMENT DU TERRITOIRE'
    WHEN 'IMIN' THEN 'INGENIERIE MINIERE'
    WHEN 'IPE' THEN 'INGENIERIE PETROLIERE'
    WHEN 'ISA' THEN 'INGENIERIE DES SYSTEMES AVANCES'
    WHEN 'MTO' THEN 'METEOROLOGIE'
    WHEN 'SIM' THEN 'SCIENCES ET INGENIERIE DES MATERIAUX'
    WHEN 'TCO' THEN 'TELECOMMUNICATION'
    WHEN 'UAGC' THEN 'URBANISME, ARCHITECTURE ET GENIE CIVIL'
    ELSE nom
END;

-- UPDATE mentions
-- SET abr = CASE nom
--     WHEN 'BTP' THEN 'BTP'
--     WHEN 'EN' THEN 'EN'
--     WHEN 'GE' THEN 'GE'
--     WHEN 'GER' THEN 'GER'
--     WHEN 'GGEO' THEN 'GGEO'
--     WHEN 'GMI' THEN 'GMI'
--     WHEN 'GPCI' THEN 'GPCI'
--     WHEN 'HYD' THEN 'HYD'
--     WHEN 'IGAT' THEN 'IGAT'
--     WHEN 'IMIN' THEN 'IMIN'
--     WHEN 'IPE' THEN 'IPE'
--     WHEN 'ISA' THEN 'ISA'
--     WHEN 'MTO' THEN 'MTO'
--     WHEN 'SIM' THEN 'SIM'
--     WHEN 'TCO' THEN 'TCO'
--     WHEN 'UAGC' THEN 'UAGC'
--     ELSE nom
-- END;